name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: yilinwei/setup-ammonite@master
        with:
          ammonite-version: 2.2.0
          scala-version: 2.13
      - name: Pre-clean
        run: rm -rf _site
      - name: Setup worktree
        run: git worktree add -B gh-pages _site refs/remotes/origin/gh-pages
      - name: Build
        run: amm blog.sc
      - name: Test generated
        run: ls -al _site
      - name: Push to gh-pages
        run: |
          git config user.email 'subatomic_bot@users.noreply.github.com'
          git config user.name 'subatomic_bot'
          git remote add gh-token "https://${{secrets.GITHUB_TOKEN}}@github.com/indoorvivants/subatomic.git"
          cd _site
          git add --all
          (git diff-index --quiet HEAD || git commit -m 'Publishing to gh-pages')
          cd ..
          git push gh-token gh-pages