name: Publish site

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: yilinwei/setup-ammonite@master
        with:
          ammonite-version: 2.2.0
          scala-version: 2.13
      - name: Build
        run: amm blog.sc
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
