name: Publish site

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: laughedelic/coursier-setup@v1
        with:
          apps: ammonite
      - name: Build
        run: ./ammonite blog.sc --destination ${PWD}/_site --overwrite
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
